# Site settings
title: Litteratur-Tafel
email: frank.fischer@sub.uni-goettingen.de
description: "Digitalisation and Indexing of Cäsar Flaischlen's \"Graphische Litteratur-Tafel\" (1890)"
baseurl: "http://data.weltliteratur.net/litteratur-tafel/"
url: "http://data.weltliteratur.net/litteratur-tafel/"
twitter_username: 
github_username:  weltliteratur

# Build settings
markdown: kramdown
permalink: pretty
